package com.sjydvlp.elefx.component.icon;

/**
 * Element Plus SVG icon types.
 *
 * <p>
 * SVG resources are sourced from the Element Plus icon collection and
 * normalized to a 24 by 24 outer view box.
 * </p>
 *
 * @author sjydvlp@163.com
 * @date 2026/9/6
 */
public enum EleFXIconType {

    ADD_LOCATION("add-location", "svg/add-location.svg"),
    AIM("aim", "svg/aim.svg"),
    ALARM_CLOCK("alarm-clock", "svg/alarm-clock.svg"),
    APPLE("apple", "svg/apple.svg"),
    ARROW_DOWN_BOLD("arrow-down-bold", "svg/arrow-down-bold.svg"),
    ARROW_DOWN("arrow-down", "svg/arrow-down.svg"),
    ARROW_LEFT_BOLD("arrow-left-bold", "svg/arrow-left-bold.svg"),
    ARROW_LEFT("arrow-left", "svg/arrow-left.svg"),
    ARROW_RIGHT_BOLD("arrow-right-bold", "svg/arrow-right-bold.svg"),
    ARROW_RIGHT("arrow-right", "svg/arrow-right.svg"),
    ARROW_UP_BOLD("arrow-up-bold", "svg/arrow-up-bold.svg"),
    ARROW_UP("arrow-up", "svg/arrow-up.svg"),
    AVATAR("avatar", "svg/avatar.svg"),
    BACK("back", "svg/back.svg"),
    BASEBALL("baseball", "svg/baseball.svg"),
    BASKETBALL("basketball", "svg/basketball.svg"),
    BELL_FILLED("bell-filled", "svg/bell-filled.svg"),
    BELL("bell", "svg/bell.svg"),
    BICYCLE("bicycle", "svg/bicycle.svg"),
    BOTTOM_LEFT("bottom-left", "svg/bottom-left.svg"),
    BOTTOM_RIGHT("bottom-right", "svg/bottom-right.svg"),
    BOTTOM("bottom", "svg/bottom.svg"),
    BOWL("bowl", "svg/bowl.svg"),
    BOX("box", "svg/box.svg"),
    BRIEFCASE("briefcase", "svg/briefcase.svg"),
    BRUSH_FILLED("brush-filled", "svg/brush-filled.svg"),
    BRUSH("brush", "svg/brush.svg"),
    BURGER("burger", "svg/burger.svg"),
    CALENDAR("calendar", "svg/calendar.svg"),
    CAMERA_FILLED("camera-filled", "svg/camera-filled.svg"),
    CAMERA("camera", "svg/camera.svg"),
    CARET_BOTTOM("caret-bottom", "svg/caret-bottom.svg"),
    CARET_LEFT("caret-left", "svg/caret-left.svg"),
    CARET_RIGHT("caret-right", "svg/caret-right.svg"),
    CARET_TOP("caret-top", "svg/caret-top.svg"),
    CELLPHONE("cellphone", "svg/cellphone.svg"),
    CHAT_DOT_ROUND("chat-dot-round", "svg/chat-dot-round.svg"),
    CHAT_DOT_SQUARE("chat-dot-square", "svg/chat-dot-square.svg"),
    CHAT_LINE_ROUND("chat-line-round", "svg/chat-line-round.svg"),
    CHAT_LINE_SQUARE("chat-line-square", "svg/chat-line-square.svg"),
    CHAT_ROUND("chat-round", "svg/chat-round.svg"),
    CHAT_SQUARE("chat-square", "svg/chat-square.svg"),
    CHECK("check", "svg/check.svg"),
    CHECKED("checked", "svg/checked.svg"),
    CHERRY("cherry", "svg/cherry.svg"),
    CHICKEN("chicken", "svg/chicken.svg"),
    CHROME_FILLED("chrome-filled", "svg/chrome-filled.svg"),
    CIRCLE_CHECK_FILLED("circle-check-filled", "svg/circle-check-filled.svg"),
    CIRCLE_CHECK("circle-check", "svg/circle-check.svg"),
    CIRCLE_CLOSE_FILLED("circle-close-filled", "svg/circle-close-filled.svg"),
    CIRCLE_CLOSE("circle-close", "svg/circle-close.svg"),
    CIRCLE_PLUS_FILLED("circle-plus-filled", "svg/circle-plus-filled.svg"),
    CIRCLE_PLUS("circle-plus", "svg/circle-plus.svg"),
    CLOCK("clock", "svg/clock.svg"),
    CLOSE_BOLD("close-bold", "svg/close-bold.svg"),
    CLOSE("close", "svg/close.svg"),
    CLOUDY("cloudy", "svg/cloudy.svg"),
    COFFEE_CUP("coffee-cup", "svg/coffee-cup.svg"),
    COFFEE("coffee", "svg/coffee.svg"),
    COIN("coin", "svg/coin.svg"),
    COLD_DRINK("cold-drink", "svg/cold-drink.svg"),
    COLLECTION_TAG("collection-tag", "svg/collection-tag.svg"),
    COLLECTION("collection", "svg/collection.svg"),
    COMMENT("comment", "svg/comment.svg"),
    COMPASS("compass", "svg/compass.svg"),
    CONNECTION("connection", "svg/connection.svg"),
    COORDINATE("coordinate", "svg/coordinate.svg"),
    COPY_DOCUMENT("copy-document", "svg/copy-document.svg"),
    CPU("cpu", "svg/cpu.svg"),
    CREDIT_CARD("credit-card", "svg/credit-card.svg"),
    CROP("crop", "svg/crop.svg"),
    D_ARROW_LEFT("d-arrow-left", "svg/d-arrow-left.svg"),
    D_ARROW_RIGHT("d-arrow-right", "svg/d-arrow-right.svg"),
    D_CARET("d-caret", "svg/d-caret.svg"),
    DATA_ANALYSIS("data-analysis", "svg/data-analysis.svg"),
    DATA_BOARD("data-board", "svg/data-board.svg"),
    DATA_LINE("data-line", "svg/data-line.svg"),
    DELETE_FILLED("delete-filled", "svg/delete-filled.svg"),
    DELETE_LOCATION("delete-location", "svg/delete-location.svg"),
    DELETE("delete", "svg/delete.svg"),
    DESSERT("dessert", "svg/dessert.svg"),
    DISCOUNT("discount", "svg/discount.svg"),
    DISH_DOT("dish-dot", "svg/dish-dot.svg"),
    DISH("dish", "svg/dish.svg"),
    DOCUMENT_ADD("document-add", "svg/document-add.svg"),
    DOCUMENT_CHECKED("document-checked", "svg/document-checked.svg"),
    DOCUMENT_COPY("document-copy", "svg/document-copy.svg"),
    DOCUMENT_DELETE("document-delete", "svg/document-delete.svg"),
    DOCUMENT_REMOVE("document-remove", "svg/document-remove.svg"),
    DOCUMENT("document", "svg/document.svg"),
    DOWNLOAD("download", "svg/download.svg"),
    DRIZZLING("drizzling", "svg/drizzling.svg"),
    EDIT_PEN("edit-pen", "svg/edit-pen.svg"),
    EDIT("edit", "svg/edit.svg"),
    ELEME_FILLED("eleme-filled", "svg/eleme-filled.svg"),
    ELEME("eleme", "svg/eleme.svg"),
    ELEMENT_PLUS("element-plus", "svg/element-plus.svg"),
    EXPAND("expand", "svg/expand.svg"),
    FAILED("failed", "svg/failed.svg"),
    FEMALE("female", "svg/female.svg"),
    FILES("files", "svg/files.svg"),
    FILM("film", "svg/film.svg"),
    FILTER("filter", "svg/filter.svg"),
    FINISHED("finished", "svg/finished.svg"),
    FIRST_AID_KIT("first-aid-kit", "svg/first-aid-kit.svg"),
    FLAG("flag", "svg/flag.svg"),
    FOLD("fold", "svg/fold.svg"),
    FOLDER_ADD("folder-add", "svg/folder-add.svg"),
    FOLDER_CHECKED("folder-checked", "svg/folder-checked.svg"),
    FOLDER_DELETE("folder-delete", "svg/folder-delete.svg"),
    FOLDER_OPENED("folder-opened", "svg/folder-opened.svg"),
    FOLDER_REMOVE("folder-remove", "svg/folder-remove.svg"),
    FOLDER("folder", "svg/folder.svg"),
    FOOD("food", "svg/food.svg"),
    FOOTBALL("football", "svg/football.svg"),
    FORK_SPOON("fork-spoon", "svg/fork-spoon.svg"),
    FRIES("fries", "svg/fries.svg"),
    FULL_SCREEN("full-screen", "svg/full-screen.svg"),
    GOBLET_FULL("goblet-full", "svg/goblet-full.svg"),
    GOBLET_SQUARE_FULL("goblet-square-full", "svg/goblet-square-full.svg"),
    GOBLET_SQUARE("goblet-square", "svg/goblet-square.svg"),
    GOBLET("goblet", "svg/goblet.svg"),
    GOLD_MEDAL("gold-medal", "svg/gold-medal.svg"),
    GOODS_FILLED("goods-filled", "svg/goods-filled.svg"),
    GOODS("goods", "svg/goods.svg"),
    GRAPE("grape", "svg/grape.svg"),
    GRID("grid", "svg/grid.svg"),
    GUIDE("guide", "svg/guide.svg"),
    HANDBAG("handbag", "svg/handbag.svg"),
    HEADSET("headset", "svg/headset.svg"),
    HELP_FILLED("help-filled", "svg/help-filled.svg"),
    HELP("help", "svg/help.svg"),
    HIDE("hide", "svg/hide.svg"),
    HISTOGRAM("histogram", "svg/histogram.svg"),
    HOME_FILLED("home-filled", "svg/home-filled.svg"),
    HOT_WATER("hot-water", "svg/hot-water.svg"),
    HOUSE("house", "svg/house.svg"),
    ICE_CREAM_ROUND("ice-cream-round", "svg/ice-cream-round.svg"),
    ICE_CREAM_SQUARE("ice-cream-square", "svg/ice-cream-square.svg"),
    ICE_CREAM("ice-cream", "svg/ice-cream.svg"),
    ICE_DRINK("ice-drink", "svg/ice-drink.svg"),
    ICE_TEA("ice-tea", "svg/ice-tea.svg"),
    INFO_FILLED("info-filled", "svg/info-filled.svg"),
    IPHONE("iphone", "svg/iphone.svg"),
    KEY("key", "svg/key.svg"),
    KNIFE_FORK("knife-fork", "svg/knife-fork.svg"),
    LIGHTNING("lightning", "svg/lightning.svg"),
    LINK("link", "svg/link.svg"),
    LIST("list", "svg/list.svg"),
    LOADING("loading", "svg/loading.svg"),
    LOCATION_FILLED("location-filled", "svg/location-filled.svg"),
    LOCATION_INFORMATION("location-information", "svg/location-information.svg"),
    LOCATION("location", "svg/location.svg"),
    LOCK("lock", "svg/lock.svg"),
    LOLLIPOP("lollipop", "svg/lollipop.svg"),
    MAGIC_STICK("magic-stick", "svg/magic-stick.svg"),
    MAGNET("magnet", "svg/magnet.svg"),
    MALE("male", "svg/male.svg"),
    MANAGEMENT("management", "svg/management.svg"),
    MAP_LOCATION("map-location", "svg/map-location.svg"),
    MEDAL("medal", "svg/medal.svg"),
    MEMO("memo", "svg/memo.svg"),
    MENU("menu", "svg/menu.svg"),
    MESSAGE_BOX("message-box", "svg/message-box.svg"),
    MESSAGE("message", "svg/message.svg"),
    MIC("mic", "svg/mic.svg"),
    MICROPHONE("microphone", "svg/microphone.svg"),
    MILK_TEA("milk-tea", "svg/milk-tea.svg"),
    MINUS("minus", "svg/minus.svg"),
    MONEY("money", "svg/money.svg"),
    MONITOR("monitor", "svg/monitor.svg"),
    MOON_NIGHT("moon-night", "svg/moon-night.svg"),
    MOON("moon", "svg/moon.svg"),
    MORE_FILLED("more-filled", "svg/more-filled.svg"),
    MORE("more", "svg/more.svg"),
    MOSTLY_CLOUDY("mostly-cloudy", "svg/mostly-cloudy.svg"),
    MOUSE("mouse", "svg/mouse.svg"),
    MUG("mug", "svg/mug.svg"),
    MUTE_NOTIFICATION("mute-notification", "svg/mute-notification.svg"),
    MUTE("mute", "svg/mute.svg"),
    NO_SMOKING("no-smoking", "svg/no-smoking.svg"),
    NOTEBOOK("notebook", "svg/notebook.svg"),
    NOTIFICATION("notification", "svg/notification.svg"),
    ODOMETER("odometer", "svg/odometer.svg"),
    OFFICE_BUILDING("office-building", "svg/office-building.svg"),
    OPEN("open", "svg/open.svg"),
    OPERATION("operation", "svg/operation.svg"),
    OPPORTUNITY("opportunity", "svg/opportunity.svg"),
    ORANGE("orange", "svg/orange.svg"),
    PAPERCLIP("paperclip", "svg/paperclip.svg"),
    PARTLY_CLOUDY("partly-cloudy", "svg/partly-cloudy.svg"),
    PEAR("pear", "svg/pear.svg"),
    PHONE_FILLED("phone-filled", "svg/phone-filled.svg"),
    PHONE("phone", "svg/phone.svg"),
    PICTURE_FILLED("picture-filled", "svg/picture-filled.svg"),
    PICTURE_ROUNDED("picture-rounded", "svg/picture-rounded.svg"),
    PICTURE("picture", "svg/picture.svg"),
    PIE_CHART("pie-chart", "svg/pie-chart.svg"),
    PLACE("place", "svg/place.svg"),
    PLATFORM("platform", "svg/platform.svg"),
    PLUS("plus", "svg/plus.svg"),
    POINTER("pointer", "svg/pointer.svg"),
    POSITION("position", "svg/position.svg"),
    POSTCARD("postcard", "svg/postcard.svg"),
    POURING("pouring", "svg/pouring.svg"),
    PRESENT("present", "svg/present.svg"),
    PRICE_TAG("price-tag", "svg/price-tag.svg"),
    PRINTER("printer", "svg/printer.svg"),
    PROMOTION("promotion", "svg/promotion.svg"),
    QUARTZ_WATCH("quartz-watch", "svg/quartz-watch.svg"),
    QUESTION_FILLED("question-filled", "svg/question-filled.svg"),
    RANK("rank", "svg/rank.svg"),
    READING_LAMP("reading-lamp", "svg/reading-lamp.svg"),
    READING("reading", "svg/reading.svg"),
    REFRESH_LEFT("refresh-left", "svg/refresh-left.svg"),
    REFRESH_RIGHT("refresh-right", "svg/refresh-right.svg"),
    REFRESH("refresh", "svg/refresh.svg"),
    REFRIGERATOR("refrigerator", "svg/refrigerator.svg"),
    REMOVE_FILLED("remove-filled", "svg/remove-filled.svg"),
    REMOVE("remove", "svg/remove.svg"),
    RIGHT("right", "svg/right.svg"),
    SCALE_TO_ORIGINAL("scale-to-original", "svg/scale-to-original.svg"),
    SCHOOL("school", "svg/school.svg"),
    SCISSOR("scissor", "svg/scissor.svg"),
    SEARCH("search", "svg/search.svg"),
    SELECT("select", "svg/select.svg"),
    SELL("sell", "svg/sell.svg"),
    SEMI_SELECT("semi-select", "svg/semi-select.svg"),
    SERVICE("service", "svg/service.svg"),
    SET_UP("set-up", "svg/set-up.svg"),
    SETTING("setting", "svg/setting.svg"),
    SHARE("share", "svg/share.svg"),
    SHIP("ship", "svg/ship.svg"),
    SHOP("shop", "svg/shop.svg"),
    SHOPPING_BAG("shopping-bag", "svg/shopping-bag.svg"),
    SHOPPING_CART_FULL("shopping-cart-full", "svg/shopping-cart-full.svg"),
    SHOPPING_CART("shopping-cart", "svg/shopping-cart.svg"),
    SHOPPING_TROLLEY("shopping-trolley", "svg/shopping-trolley.svg"),
    SMOKING("smoking", "svg/smoking.svg"),
    SOCCER("soccer", "svg/soccer.svg"),
    SOLD_OUT("sold-out", "svg/sold-out.svg"),
    SORT_DOWN("sort-down", "svg/sort-down.svg"),
    SORT_UP("sort-up", "svg/sort-up.svg"),
    SORT("sort", "svg/sort.svg"),
    STAMP("stamp", "svg/stamp.svg"),
    STAR_FILLED("star-filled", "svg/star-filled.svg"),
    STAR("star", "svg/star.svg"),
    STOPWATCH("stopwatch", "svg/stopwatch.svg"),
    SUCCESS_FILLED("success-filled", "svg/success-filled.svg"),
    SUGAR("sugar", "svg/sugar.svg"),
    SUITCASE_LINE("suitcase-line", "svg/suitcase-line.svg"),
    SUITCASE("suitcase", "svg/suitcase.svg"),
    SUNNY("sunny", "svg/sunny.svg"),
    SUNRISE("sunrise", "svg/sunrise.svg"),
    SUNSET("sunset", "svg/sunset.svg"),
    SWITCH_BUTTON("switch-button", "svg/switch-button.svg"),
    SWITCH_FILLED("switch-filled", "svg/switch-filled.svg"),
    SWITCH("switch", "svg/switch.svg"),
    TAKEAWAY_BOX("takeaway-box", "svg/takeaway-box.svg"),
    TICKET("ticket", "svg/ticket.svg"),
    TICKETS("tickets", "svg/tickets.svg"),
    TIMER("timer", "svg/timer.svg"),
    TOILET_PAPER("toilet-paper", "svg/toilet-paper.svg"),
    TOOLS("tools", "svg/tools.svg"),
    TOP_LEFT("top-left", "svg/top-left.svg"),
    TOP_RIGHT("top-right", "svg/top-right.svg"),
    TOP("top", "svg/top.svg"),
    TREND_CHARTS("trend-charts", "svg/trend-charts.svg"),
    TROPHY_BASE("trophy-base", "svg/trophy-base.svg"),
    TROPHY("trophy", "svg/trophy.svg"),
    TURN_OFF("turn-off", "svg/turn-off.svg"),
    UMBRELLA("umbrella", "svg/umbrella.svg"),
    UNLOCK("unlock", "svg/unlock.svg"),
    UPLOAD_FILLED("upload-filled", "svg/upload-filled.svg"),
    UPLOAD("upload", "svg/upload.svg"),
    USER_FILLED("user-filled", "svg/user-filled.svg"),
    USER("user", "svg/user.svg"),
    VAN("van", "svg/van.svg"),
    VIDEO_CAMERA_FILLED("video-camera-filled", "svg/video-camera-filled.svg"),
    VIDEO_CAMERA("video-camera", "svg/video-camera.svg"),
    VIDEO_PAUSE("video-pause", "svg/video-pause.svg"),
    VIDEO_PLAY("video-play", "svg/video-play.svg"),
    VIEW("view", "svg/view.svg"),
    WALLET_FILLED("wallet-filled", "svg/wallet-filled.svg"),
    WALLET("wallet", "svg/wallet.svg"),
    WARN_TRIANGLE_FILLED("warn-triangle-filled", "svg/warn-triangle-filled.svg"),
    WARNING_FILLED("warning-filled", "svg/warning-filled.svg"),
    WARNING("warning", "svg/warning.svg"),
    WATCH("watch", "svg/watch.svg"),
    WATERMELON("watermelon", "svg/watermelon.svg"),
    WIND_POWER("wind-power", "svg/wind-power.svg"),
    ZOOM_IN("zoom-in", "svg/zoom-in.svg"),
    ZOOM_OUT("zoom-out", "svg/zoom-out.svg");

    private final String name;

    private final String path;

    EleFXIconType(String name, String path) {
        this.name = name;
        this.path = path;
    }

    public String iconName() {
        return name;
    }

    public String path() {
        return path;
    }

    public String styleClass() {
        return "ele-icon--" + name;
    }

    public String svgResourcePath() {
        return path();
    }

    public String svgPathData() {
        return EleFXIconResources.pathData(this);
    }
}
